
package accuproducer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "accuServiceInterface", targetNamespace = "http://nl.hu.iac/accuservice/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccuServiceInterface {


    /**
     * 
     * @param request
     * @return
     *     returns accuproducer.AccuResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "accuResponse", targetNamespace = "http://nl.hu.iac/accuservice/response", partName = "response")
    public AccuResponse calculateAccuPercentage(
        @WebParam(name = "accuRequest", targetNamespace = "http://nl.hu.iac/accuservice/request", partName = "request")
        AccuRequest request)
        throws Fault
    ;

}
