
package accuproducer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "accuFault", targetNamespace = "http://nl.hu.iac/accuservice/faultCheck")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AccuFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, AccuFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, AccuFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: accuproducer.AccuFault
     */
    public AccuFault getFaultInfo() {
        return faultInfo;
    }

}
